### ISSUE TITLE
Cannot Access LDAP Directory - User Password reset

### ISSUE THREAD

**Issue by ranyhs** [ltb-project/self-service-password#500]
Hello all,

I can confirm working a Password reset with using  $who_change_password = "manager";
We do not want a password stored in plain text.

Reviewing the credentials page here:
https://ltb-project.org/documentation/self-service-password/latest/config_ldap#active_directory
I have set the $ldap_binddn = ""; $ldap_bindpw = ""; to  blank.

We then get the following error: 
 Cannot access LDAP directory
Warning: ldap_search(): Search: Operations error in D:\Password Website\pages\change.php on line 95

`# LDAP
$ldap_url = "ldaps://DC.Domain.com";
$ldap_starttls = false;
#$ldap_bindpw = "XYZSecret";
#$ldap_binddn = "CN=Password Admin,OU OU OUl";
$ldap_binddn = "";
$ldap_bindpw = "";
$ldap_base = "OU=OU OU";
#$ldap_login_attribute = "uid";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
`
`$ad_mode = true;`
` $who_change_password = "user";`

I can't have a plaintext password in a document that can reset any password in the domain. 
Please let me know where I'm going wrong here!  :-)

**Comment by faust64** [comment]
Hi,

When `$who_change_password = "manager";`, it is assumed SSP would bind to your LDAP using the `$ldap_binddn` & `$ldap_bindpw`.

On the other hand, if you want the user to change his password, binding with his own account, then you want to set `$who_change_password = "user";` . Then, SSP would not rely on a manager account.

See: https://self-service-password.readthedocs.io/en/v1.4/config_ldap.html#credentials

And consider updating to v1.4, which has been released lately.
Otherwise, running v1.3 (`pages/change.php` log), the previous doc would be more accurate: https://ltb-project.org/documentation/self-service-password/1.3/config_ldap

Regards.

**Comment by ranyhs** [comment]
Hi Faust,

Thanks for the reply.

Thats what I'm doing - $who_change_password = "user"; 

and both 

$ldap_binddn = "";
$ldap_bindpw = "";

are set to blank.

I just updated to 1.4. However, still getting the error 

Cannot access LDAP directory
Warning: ldap_search(): Search: Operations error in D:\Password Website\pages\change.php on line 95

What are my next steps to do to diagnose the cause of this?

**Comment by faust64** [comment]
If the `who_change_password` was already set to user, then this message would suggest we can not search the directory after an anonymous bind, before logging in as the user changing its password.

Then, maybe you should still put some credentials into your configuration (`$ldap_binddn` & `$ldap_bindpw`), ensuring that user have enough privileges to search for users in your directory - mostly ensure the attributes from your `$ldap_filter` as well as your `$mail_attribute` can be searched (read), no write privileges necessary.

**Comment by coudot** [comment]
@ranyhs Hi. Active Directory does not allow to read entries anonymously. As said by @faust64 you must a technical account to search the directory. This account can be a simple user account with no special privileges if you configure `$who_change_password` to `user`, then the technical account will not be used for password modifiy, for the standard change screen.

As written in documentation, the technical account is used to modify password for all reset features, because in this we don't have the old password of the user, so we can't use his account to change the password.

**Comment by ranyhs** [comment]
Thank you for your input on this one.
I created an LDAP.Reader account with Read permission to the respective branches required. 
This account (LDAP.Reader) has been set to the $ldap_binddn and $ldap_bindpw.

 $who_change_password is still set to user. 
I no longer get the LDAP Search error. 

The user I am using [Test.User] can change its own password and it can change its own password to the one I am trying. So that removes that part.

Issue being observed: 
Warning: ldap_modify_batch(): Batch Modify: Constraint violation in D:\Password Website\lib\functions.inc.php on line 396
Password was refused by the LDAP directory

Its as is 'Test.User' cannot change its own password or the portal is trying to use the LDAP.Reader account to set the password.


How am I best placed to drill down to find out whats causing the error to throw?

**Comment by coudot** [comment]
Most of the time "Constraint violation" means the submitted password is not strong enough, so refused by AD. Check your password policy settings on AD.

**Comment by ranyhs** [comment]
To confirm - I have reset to this password in AD. The password is valid and accepted via AD GUI.

It appears that when '$who_change_password = user' that user cannot reset their own password using the portal.
I have given that user [Test.User]  delegated password reset right to a specific OU [TestOU] where the user [Test.User] is now residing. 

Same error: 

Warning: ldap_modify_batch(): Batch Modify: Constraint violation in D:\Password Website\lib\functions.inc.php on line 396
Password was refused by the LDAP directory

To confirm, the password being set is accepted by AD in the GUI.

**Comment by coudot** [comment]
Are you sure to have configured LDAPS to connect to Active Directory? This is mandatory.

**Comment by ranyhs** [comment]
Absolutely - the LDAPS connection works fine with the user set to manager.

Has anyone been able to set the user to change the password to **'$who_change_password = user'** ? 
It seems most people are using manager instead of user. The manager account is then given delegated rights to reset all user accounts.

How can we have the user and only the user set their own password? 
It would be security best practice to not have a password in plain text that can reset any user in the domain. 

What's the best way to resolve this?

**Comment by coudot** [comment]
Hi @ranyhs 

thanks for the details. Sadly I don't know how to resolve this. Seems the code was working for older AD versions but maybe not for recent ones. If you can find which exact LDAP operations are needed to change the password as user, we can adapt our code.

**Comment by ranyhs** [comment]
Hello,

Thanks for the heads up.

Would this be correct?

ldappasswd -H ldap://server_domain_or_IP -x -D "user's_dn" -w old_passwd -a
old_passwd -S
or
Changing a User’s Password Using the RootDN Bind
ldappasswd -H ldap://server_domain_or_IP -x -D "cn=admin,dc=example,dc=com"
-W -S "uid=bob,ou=people,dc=example,dc=com"

This technet has decent info - does this nail what we're trying to achieve?

https://social.technet.microsoft.com/Forums/lync/en-US/c0a41fec-4390-4b74-89eb-9299691a3e33/allow-user-to-bind-and-filter-ldap-and-change-password?forum=winserversecurity
<goog_1872365855>
http://windowsitpro.com/active-directory/advanced-active-directory-security

I'm more than happy to work with and test this with you.




AD

You chose to delegate control of objects
in the following Active Directory folder:

    OUOU/Staff/Temp Staff

The groups, users, or computers to which you
have given control are:

    Maintenance User (muser@Domain.local)

They have the following permissions:

    Change password
    Reset password

For the following object types:

    User



Dan Pritchard | Technology Support

T 604.736.6551 Ext 150 <604.736.6551;150> E ***@***.***

4176 Alexandra Street, Vancouver, BC,  V6J 2V6

<https://www.facebook.com/yorkhouseschool/>
<https://twitter.com/yorkhouseschool?lang=en>
<https://www.instagram.com/yorkhousevan/>
<https://www.youtube.com/user/yorkhousedotca> <http://www.yorkhouse.ca/>

NOTE: This e-mail message is intended for the named recipient(s) above, and
may contain information that is privileged, confidential, and/or exempt
from disclosure under applicable law. If you have received this message in
error, or are not the named recipient(s), please do not read the content.
Instead, immediately notify the sender and delete this e-mail message. Any
unauthorized use, disclosure, or distribution is prohibited. York House
School and the sender assume no responsibility for any errors or omissions
in the content or transmission of this e-mail.

**Comment by coudot** [comment]
Looking at this official documentation, we are doing the right thing: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2?redirectedfrom=MSDN

> If the Modify request contains a delete operation containing a value Vdel for unicodePwd followed by an add operation containing a value Vadd for unicodePwd, the server considers the request to be a request to change the password. The server decodes Vadd and Vdel using the password decoding procedure documented later in this section. Vdel is the old password, while Vadd is the new password.

> For the password change operation to succeed, the server enforces the requirement that the user or inetOrgPerson object whose password is being changed must possess the "User-Change-Password" control access right on itself, and that Vdel must be the current password on the object

In our code:
```php
        $oldpassword = make_ad_password($oldpassword);

        $modifications = array(
            array(
                "attrib" => "unicodePwd",
                "modtype" => LDAP_MODIFY_BATCH_REMOVE,
                "values" => array($oldpassword),
            ),
            array(
                "attrib" => "unicodePwd",
                "modtype" => LDAP_MODIFY_BATCH_ADD,
                "values" => array($password),
            ),
        );

        $bmod = ldap_modify_batch($ldap, $dn, $modifications);
```

Either the old password you use is incorrect, either the new password does not fit the password policy constraints.

**Comment by ranyhs** [comment]
I hear what your saying.

The password I'm using : "Jumping300@!" can be set in AD and can be set by
the manager account with password resert delegated rights on the OU in
question.
The old (current) password - I'm using currently.

To confirm:
- Current password is correct
- New password is accepted by AD and LTB when set by the manager.


How can I get you logs or further information to investigate what's going
on here?



Dan Pritchard | Technology Support

T 604.736.6551 Ext 150 <604.736.6551;150> E ***@***.***

4176 Alexandra Street, Vancouver, BC,  V6J 2V6

<https://www.facebook.com/yorkhouseschool/>
<https://twitter.com/yorkhouseschool?lang=en>
<https://www.instagram.com/yorkhousevan/>
<https://www.youtube.com/user/yorkhousedotca> <http://www.yorkhouse.ca/>

NOTE: This e-mail message is intended for the named recipient(s) above, and
may contain information that is privileged, confidential, and/or exempt
from disclosure under applicable law. If you have received this message in
error, or are not the named recipient(s), please do not read the content.
Instead, immediately notify the sender and delete this e-mail message. Any
unauthorized use, disclosure, or distribution is prohibited. York House
School and the sender assume no responsibility for any errors or omissions
in the content or transmission of this e-mail.

**Comment by coudot** [comment]
You can first set debug to true in SSP. But this will not really help to understand why AD is rejecting the change. You must get logs on AD side. Good luck...

**Comment by coudot** [comment]
Hello @ranyhs 

I was able to access to an Active Directory today.

I used this configuration:
```php
$ldap_url = "ldaps://ad.example.com";
$ldap_starttls = false;
$ldap_binddn = "cn=system,ou=system,dc=example,dc=com";
$ldap_bindpw = "Secret";
$ldap_base = "dc=example,dc=com";
$ldap_login_attribute = "sAMAccountName";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=user)($ldap_login_attribute={login}))";
$ldap_use_exop_passwd = false;
$ldap_use_ppolicy_control = false;

$ad_mode = true;
$ad_options['force_unlock'] = true;
$ad_options['force_pwd_change'] = false;
$ad_options['change_expired_password'] = true;

$who_change_password = "user";
$keyphrase = "demo";
```

I was able to change my password as user trough SSP.

**Comment by ranyhs** [comment]
Thanks! I think we're getting near.

When debug is on I get the following:


Warning: ldap_modify_batch(): Batch Modify: Constraint violation in D:\Password
Website\lib\functions.inc.php on line 396

Notice: Undefined variable: obscure_failure_messages in D:\Password
Website\pages\change.php on line 186

Warning: in_array() expects parameter 2 to be array, null given in D:\Password
Website\pages\change.php on line 186

 Password was refused by the LDAP directory

Notice: Undefined variable: display_posthook_error in D:\Password
Website\pages\change.php on line 193




Dan Pritchard | Technology Support

T 604.736.6551 Ext 150 <604.736.6551;150> E ***@***.***

4176 Alexandra Street, Vancouver, BC,  V6J 2V6

<https://www.facebook.com/yorkhouseschool/>
<https://twitter.com/yorkhouseschool?lang=en>
<https://www.instagram.com/yorkhousevan/>
<https://www.youtube.com/user/yorkhousedotca> <http://www.yorkhouse.ca/>

NOTE: This e-mail message is intended for the named recipient(s) above, and
may contain information that is privileged, confidential, and/or exempt
from disclosure under applicable law. If you have received this message in
error, or are not the named recipient(s), please do not read the content.
Instead, immediately notify the sender and delete this e-mail message. Any
unauthorized use, disclosure, or distribution is prohibited. York House
School and the sender assume no responsibility for any errors or omissions
in the content or transmission of this e-mail.

**Comment by coudot** [comment]
Sorry to repeat myself but "Constraint violation" is most of the time returned because password value is too weak.

And you should try to use the latest stable version (1.4.1)

**Comment by ranyhs** [comment]
Thanks for the update - i appreciate your assistance with this.
The Password changing to is 100% ok. Can use it in AD and another change
tool.

After upgrading the code to 1.4.1 the error messages are leading to a
variable issue.

Fatal error: Uncaught ArgumentCountError: Too few arguments to function
check_password_strength(), 4 passed in D:\Password Website\pages\change.php
on line 169 and exactly 5 expected in D:\Password
Website\lib\functions.inc.php:212 Stack trace: #0 D:\Password
Website\pages\change.php(169): check_password_strength('Shine3000&&2',
'Software2021$', Array, 'muser') #1 D:\Password Website\index.php(224):
include('D:\\Password Web...') #2 {main} thrown in D:\Password
Website\lib\functions.inc.php on line 212

function check_password_strength( $password, $oldpassword,
$pwd_policy_config, $login, $entry ) {

It looks like the variable is missing is *$entry*.

As a test - I removed the variable from the function and that cascaded to
the below error.

Fatal error: Uncaught ArgumentCountError: Too few arguments to function
change_password(), 12 passed in D:\Password Website\pages\change.php on
line 176 and exactly 14 expected in D:\Password
Website\lib\functions.inc.php:328 Stack trace: #0 D:\Password
Website\pages\change.php(176): change_password(Resource id #15,
'CN=Maintenance ...', 'Shine3000&&2', true, Array, false, Array, Array,
'clear', Array, 'user', 'Software2021$') #1 D:\Password
Website\index.php(224): include('D:\\Password Web...') #2 {main}
thrown in D:\Password
Website\lib\functions.inc.php on line 328


function change_password( $ldap, $dn, $password, $ad_mode, $ad_options,
$samba_mode, $samba_options, $shadow_options, $hash, $hash_options,
$who_change_password, $oldpassword, $use_exop_passwd, $use_ppolicy_control
) {

So this makes sense if the program cannot run the  function
check_password_strength. Thats why the code is telling us that the password
is refused.

Ever seen this error before?


Fatal error: Uncaught ArgumentCountError: Too few arguments to function
check_password_strength(), 4 passed in D:\Password Website\pages\change.php
on line 169 and exactly 5 expected in D:\Password
Website\lib\functions.inc.php:212 Stack trace: #0 D:\Password
Website\pages\change.php(169): check_password_strength('Shine3000&&2',
'Software2021$', Array, 'muser') #1 D:\Password Website\index.php(224):
include('D:\\Password Web...') #2 {main} thrown in D:\Password
Website\lib\functions.inc.php on line 212






Dan Pritchard | Technology Support

T 604.736.6551 Ext 150 <604.736.6551;150> E ***@***.***

4176 Alexandra Street, Vancouver, BC,  V6J 2V6

<https://www.facebook.com/yorkhouseschool/>
<https://twitter.com/yorkhouseschool?lang=en>
<https://www.instagram.com/yorkhousevan/>
<https://www.youtube.com/user/yorkhousedotca> <http://www.yorkhouse.ca/>

NOTE: This e-mail message is intended for the named recipient(s) above, and
may contain information that is privileged, confidential, and/or exempt
from disclosure under applicable law. If you have received this message in
error, or are not the named recipient(s), please do not read the content.
Instead, immediately notify the sender and delete this e-mail message. Any
unauthorized use, disclosure, or distribution is prohibited. York House
School and the sender assume no responsibility for any errors or omissions
in the content or transmission of this e-mail.

**Comment by faust64** [comment]
That's weird: in 1.4.1, line 169 of the change.php is 

```
168:        # Rebind as Manager if needed
169:        if ( $who_change_password == "manager" ) {
170:            $bind = ldap_bind($ldap, $ldap_binddn, $ldap_bindpw);
171:        }
```

The check_password_strength should be called on line 181 instead.
Although, even in v1.3, line doesn't match.
Then again, the `pages` subfolder looks like 1.3. In 1.4.x, it's been moved to `htdocs`.
And the check_password_strength had 4 arguments ...

Sounds like you're running a mix of 1.3 and 1.4 code.
Revert your changes on lib/functions. The issue is more likely with the change.php file. Maybe other php from the `./htdocs` as well. Make sure you have that `htdocs` subfolder in your copy of selfservicepassword, and make sure your webserver would serve PHP assets from that folder, and not the old one -- then remove the old one, to avoid confusion.

**Comment by ranyhs** [comment]
Ok. I'm going to scrub the whole thing and redeploy from scratch. Will get
back to you - thankyou for your time!



Dan Pritchard | Technology Support

T 604.736.6551 Ext 150 <604.736.6551;150> E ***@***.***

4176 Alexandra Street, Vancouver, BC,  V6J 2V6

<https://www.facebook.com/yorkhouseschool/>
<https://twitter.com/yorkhouseschool?lang=en>
<https://www.instagram.com/yorkhousevan/>
<https://www.youtube.com/user/yorkhousedotca> <http://www.yorkhouse.ca/>

NOTE: This e-mail message is intended for the named recipient(s) above, and
may contain information that is privileged, confidential, and/or exempt
from disclosure under applicable law. If you have received this message in
error, or are not the named recipient(s), please do not read the content.
Instead, immediately notify the sender and delete this e-mail message. Any
unauthorized use, disclosure, or distribution is prohibited. York House
School and the sender assume no responsibility for any errors or omissions
in the content or transmission of this e-mail.
